In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Environment ready!")

Environment ready!

In [38]:
import os

file_path = "../data/raw/PS_20174392719_1491204439457_log.csv"

print("File exists:", os.path.exists(file_path))

File exists: True

In [39]:
df_sample = pd.read_csv(file_path, nrows=10000)

print("Sample shape:", df_sample.shape)
print("\nColumns:")
print(df_sample.columns.tolist())

Sample shape: (10000, 11)

Columns:
['step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg', 'newbalanceOrig', 'nameDest', 'oldbalanceDest', 'newbalanceDest', 'isFraud', 'isFlaggedFraud']

In [40]:
df_sample.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,0

In [41]:
df_sample.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   step            10000 non-null  int64
 1   type            10000 non-null  str
 2   amount          10000 non-null  float64
 3   nameOrig        10000 non-null  str
 4   oldbalanceOrg   10000 non-null  float64
 5   newbalanceOrig  10000 non-null  float64
 6   nameDest        10000 non-null  str
 7   oldbalanceDest  10000 non-null  float64
 8   newbalanceDest  10000 non-null  float64
 9   isFraud         10000 non-null  int64
 10  isFlaggedFraud  10000 non-null  int64
dtypes: float64(5), int64(3), str(3)
memory usage: 1.1 MB

In [42]:
print("Transaction types:")
print(df_sample["type"].value_counts())

print("\nFraud distribution:")
print(df_sample["isFraud"].value_counts())

print("\nFraud percentage:")
print(df_sample["isFraud"].mean() * 100)

Transaction types:
type
PAYMENT     5465
CASH_IN     1949
CASH_OUT    1321
TRANSFER     921
DEBIT        344
Name: count, dtype: int64

Fraud distribution:
isFraud
0    9932
1      68
Name: count, dtype: int64

Fraud percentage:
0.6799999999999999

In [43]:
print("Number of unique senders:", df_sample["nameOrig"].nunique())
print("Number of unique receivers:", df_sample["nameDest"].nunique())
print("Number of time steps:", df_sample["step"].nunique())

Number of unique senders: 10000
Number of unique receivers: 6397
Number of time steps: 7

In [44]:
print(df_sample.groupby("type")["isFraud"].agg(["count", "sum", "mean"]))

          count  sum      mean
type
CASH_IN    1949    0  0.000000
CASH_OUT   1321   35  0.026495
DEBIT       344    0  0.000000
PAYMENT    5465    0  0.000000
TRANSFER    921   33  0.035831

In [45]:
import os

file_size_mb = os.path.getsize(file_path) / (1024 ** 2)

print(f"File size: {file_size_mb:.1f} MB")

File size: 470.7 MB

In [46]:
with open(file_path, "r", encoding="utf-8") as f:
    total_rows = sum(1 for _ in f) - 1

print(f"Total transactions: {total_rows:,}")

Total transactions: 6,362,620

In [47]:
df = pd.read_csv(file_path)

print("Shape:", df.shape)
print(f"Memory used: {df.memory_usage(deep=True).sum() / (1024**3):.2f} GB")

Shape: (6362620, 11)
Memory used: 0.69 GB

In [48]:
df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,0

In [49]:
df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [50]:
fraud_counts = df["isFraud"].value_counts()

print(fraud_counts)
print("\nFraud percentage:")
print(df["isFraud"].mean() * 100)

isFraud
0    6354407
1       8213
Name: count, dtype: int64

Fraud percentage:
0.12908204481801522

In [51]:
df["type"].value_counts()

type
CASH_OUT    2237500
PAYMENT     2151495
CASH_IN     1399284
TRANSFER     532909
DEBIT         41432
Name: count, dtype: int64

In [52]:
fraud_by_type = df.groupby("type")["isFraud"].agg(
    transactions="count",
    fraud_cases="sum",
    fraud_rate="mean"
)

fraud_by_type["fraud_rate"] *= 100

fraud_by_type

          transactions  fraud_cases  fraud_rate
type
CASH_IN        1399284            0    0.000000
CASH_OUT       2237500         4116    0.183955
DEBIT            41432            0    0.000000
PAYMENT        2151495            0    0.000000
TRANSFER        532909         4097    0.768799

In [53]:
print("Minimum step:", df["step"].min())
print("Maximum step:", df["step"].max())
print("Unique steps:", df["step"].nunique())

Minimum step: 1
Maximum step: 743
Unique steps: 743

In [ ]:
df["balance_change"] = df["oldbalanceOrg"] - df["newbalanceOrig"]

df["amount_to_balance_ratio"] = (
    df["amount"] / (df["oldbalanceOrg"] + 1)
)

df["dest_balance_change"] = (
    df["newbalanceDest"] - df["oldbalanceDest"]
)

df["hour"] = df["step"] % 24

df.head()